### ISSUE TITLE
erore

### ISSUE THREAD

**Issue by igs7** [artur749343/mineproc#1]
hi, your mod does a error when start, on fabric 1.20.4

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mineproc'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:487)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
	Suppressed: java.lang.IllegalArgumentException: Builtin tab net.minecraft.class_1761@6e22204f is not registered!
		at dev.architectury.registry.fabric.CreativeTabRegistryImpl.ofBuiltin(CreativeTabRegistryImpl.java:55)
		at dev.architectury.registry.CreativeTabRegistry.ofBuiltin(CreativeTabRegistry.java)
		at dev.architectury.registry.CreativeTabRegistry.appendBuiltin(CreativeTabRegistry.java:124)
		at net.minecraft.class_1792.handler$zce000$architectury$init(class_1792.java:555)
		at net.minecraft.class_1792.<init>(class_1792.java:113)
		at net.pitan76.mcpitanlib.api.item.ExtendItem.<init>(ExtendItem.java:29)
		at net.pitan76.ygm76.item.BulletItem.<init>(BulletItem.java:8)
		at net.pitan76.ygm76.item.YGItems.lambda$init$0(YGItems.java:17)
		at dev.architectury.registry.registries.fabric.RegistrarManagerImpl$RegistrarImpl.register(RegistrarManagerImpl.java:232)
		at net.pitan76.mcpitanlib.core.registry.MCPLRegistry.registryItem(MCPLRegistry.java:48)
		at net.pitan76.mcpitanlib.api.registry.CompatRegistry.registerItem(CompatRegistry.java:75)
		at net.pitan76.ygm76.item.YGItems.init(YGItems.java:17)
		at net.pitan76.ygm76.YamatoGunMod.init(YamatoGunMod.java:27)
		at net.pitan76.ygm76.fabric.YamatoGunModFabric.onInitialize(YamatoGunModFabric.java:9)
		at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
		... 9 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_8785
	at net.kruassan.mineproc.recipe.FormCrafterRecipe$Serializer.lambda$static$2(FormCrafterRecipe.java:89)
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72)
	at net.kruassan.mineproc.recipe.FormCrafterRecipe$Serializer.<clinit>(FormCrafterRecipe.java:87)
	at net.kruassan.mineproc.recipe.ModRecipes.registerRecipes(ModRecipes.java:14)
	at net.kruassan.mineproc.Mineproc.onInitialize(Mineproc.java:78)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_8785
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 15 more

```

fix asap

**Comment by artur749343** [comment]
The problem is that my mod only supports 1.20.2. Today I plan to add for 1.20.4

**Comment by artur749343** [comment]
try this https://modrinth.com/mod/mineproc/version/fAKdeAMn

**Comment by artur749343** [comment]
try this https://modrinth.com/mod/mineproc/version/MxAhdhiX

**Comment by igs7** [comment]
It's still broken
```

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mineproc'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.7.jar:?]
        at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[server.jar:1.0.0]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_304
        at net.kruassan.mineproc.Mineproc.onInitialize(Mineproc.java:48) ~[mineproc-0.3.0-1.20.4.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
        ... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_304
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.7.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at net.kruassan.mineproc.Mineproc.onInitialize(Mineproc.java:48) ~[mineproc-0.3.0-1.20.4.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
        ... 7 more

```

**Comment by igs7** [comment]
wait no it works

**Comment by 0x7d8** [comment]
does not work for me either

**Comment by 0x7d8** [comment]
it breaks when opening a block

**Comment by artur749343** [comment]
minecraft cannot find "keyBindings" class, idk why

**Comment by artur749343** [comment]
I`m opened minecraft in 1.20.4 and all is work

**Comment by 0x7d8** [comment]
have you tried on server too?

**Comment by artur749343** [comment]
no, I thought that when opening a single player game, the game starts both as a server and as a client

**Comment by 0x7d8** [comment]
not really

**Comment by artur749343** [comment]
Well, I'm a newbie, I didn't know :(

**Comment by artur749343** [comment]
okay it actually produces this error

**Comment by artur749343** [comment]
okay i fix it try this https://modrinth.com/mod/mineproc/version/r7tyv2Kg

**Comment by igs7** [comment]
it seems to crash with very similar error when trying to use it

**Comment by artur749343** [comment]
It works for me on both the server and the client. I have no idea what i am doing wrong

**Comment by 0x7d8** [comment]
can you send your server files in a zip, may be something else

**Comment by artur749343** [comment]
I realized what the problem is, I'm an idiot who pressed the wrong button. I finded bug

**Comment by artur749343** [comment]
only now I don't know how to solve it

**Comment by artur749343** [comment]
i have no idea how fix it

**Comment by artur749343** [comment]
i need to get Entity Block from server side like this: 
FormCrafterEntity entity=//something do to get entity from server side

**Comment by artur749343** [comment]
I fixed bug

**Comment by artur749343** [comment]
I will release a working version with an update
